-- ====================================================
-- Procedimiento: Lista EQUIPOS
IF OBJECT_ID('SP_LISTAEQUIPOS') IS NOT NULL
	DROP PROC SP_LISTAEQUIPOS
	PRINT 'PROC SP_LISTAEQUIPOS, HA SIDO PROCESADO'
GO

CREATE PROC SP_LISTAEQUIPOS
AS
	SELECT
		E.IDE_EQU AS CODIGO,
		E.DESC_EQU AS DESCRIPCION,
		T.DES_TIP AS TIPO,
		E.PRE_EQU AS PRECIO,
		ES.DES_EST AS ESTADO
		FROM EQUIPO E
		JOIN TIPO_EQUIPO T ON E.COD_TIP_EQU = T.COD_TIP_EQU
		JOIN ESTADO_EQUIPO ES ON E.COD_EST=ES.COD_EST
GO

-- Procedimiento: Lista tipo EQUIPOS
IF OBJECT_ID('SP_LISTATIPOEQUIPOS') IS NOT NULL
	DROP PROC SP_LISTATIPOEQUIPOS
	PRINT 'PROC SP_LISTATIPOEQUIPOS, HA SIDO PROCESADO'
GO

CREATE PROC SP_LISTATIPOEQUIPOS
AS
	SELECT
		T.COD_TIP_EQU AS CODIGO,
		T.DES_TIP AS TIPO
		FROM TIPO_EQUIPO T
GO

-- Procedimiento: Lista ESTADOS
IF OBJECT_ID('SP_LISTAESTADOS') IS NOT NULL
	DROP PROC SP_LISTAESTADOS
	PRINT 'PROC SP_LISTAESTADOS, HA SIDO PROCESADO'
GO

CREATE PROC SP_LISTAESTADOS
AS
	SELECT
		ES.COD_EST AS CODIGO,
		ES.DES_EST AS ESTADO
		FROM ESTADO_EQUIPO ES
GO

-- Procedimiento: Obtención del Código del último registro
-- de la tabla EQUIPO
IF OBJECT_ID('SP_ULTIMOEQUIPO') IS NOT NULL
	DROP PROC SP_ULTIMOEQUIPO
	PRINT 'PROC SP_ULTIMOEQUIPO, HA SIDO PROCESADO'
GO

CREATE PROC SP_ULTIMOEQUIPO
AS
	SELECT TOP 1
		E.IDE_EQU AS CODIGO
		FROM EQUIPO E
		ORDER BY 1 DESC
GO
-- Procedimiento: Ingreso de registros en la tabla EQUIPO
IF OBJECT_ID('SP_NUEVOEQUIPO') IS NOT NULL
	DROP PROC SP_NUEVOEQUIPO
	PRINT 'PROC SP_NUEVOEQUIPO, HA SIDO PROCESADO'
GO
CREATE PROC SP_NUEVOEQUIPO
(
@COD CHAR(6), @TIP CHAR(6), @DES VARCHAR(40), @PRE MONEY, @EST INT
)
AS
	INSERT INTO EQUIPO VALUES(@COD, @TIP, @DES, @PRE, @EST)
GO

-- Procedimiento: Actualización de campos en registros en la tabla EQUIPO
IF OBJECT_ID('SP_ACTUALIZAEQUIPO') IS NOT NULL
	DROP PROC SP_ACTUALIZAEQUIPO
	PRINT 'PROC SP_ACTUALIZAEQUIPO, HA SIDO PROCESADO'
GO

CREATE PROC SP_ACTUALIZAEQUIPO
(
	@COD CHAR(6), @TIP CHAR(6), @DES VARCHAR(40), @PRE MONEY, @EST INT
)
AS
	UPDATE EQUIPO SET
		COD_TIP_EQU = @TIP,
		DESC_EQU = @DES,
		PRE_EQU = @PRE,
		COD_EST = @EST
		WHERE IDE_EQU = @COD
GO

-- Procedimiento: Eliminación de registros en la tabla EQUIPO
IF OBJECT_ID('SP_ELIMINAEQUIPO') IS NOT NULL
	DROP PROC SP_ELIMINAEQUIPO
	PRINT 'PROC SP_ELIMINAEQUIPO, HA SIDO PROCESADO'
GO

CREATE PROC SP_ELIMINAEQUIPO
(
	@COD CHAR(6)
)
AS
	DELETE EQUIPO WHERE IDE_EQU = @COD
GO

-- Scripts para los procedimientos almacenados
-- Tabla: ESTADO_EQUIPO
-- ====================================================
USE CONTRATO
GO

-- Procedimiento: Lista ESTADO_EQUIPO
IF OBJECT_ID('SP_LISTAESTADOEQUIPOS') IS NOT NULL
	DROP PROC SP_LISTAESTADOEQUIPOS
	PRINT 'PROC SP_LISTAESTADOEQUIPOS, HA SIDO PROCESADO'
GO

CREATE PROC SP_LISTAESTADOEQUIPOS
AS
	SELECT
		EE.COD_EST AS CODIGO,
		EE.DES_EST AS ESTADO
		FROM ESTADO_EQUIPO EE
GO

-- Procedimiento: Obtención del Código del último registro de la tabla ESTADO_EQUIPO
IF OBJECT_ID('SP_ULTIMOESTADOEQUIPO') IS NOT NULL
	DROP PROC SP_ULTIMOESTADOEQUIPO
	PRINT 'PROC SP_ULTIMOESTADOEQUIPO, HA SIDO PROCESADO'
GO
CREATE PROC SP_ULTIMOESTADOEQUIPO
AS
	SELECT TOP 1
		EE.COD_EST AS CODIGO
		FROM ESTADO_EQUIPO EE
		ORDER BY 1 DESC
GO

-- Procedimiento: Ingreso de registros en la tabla ESTADO_EQUIPO
IF OBJECT_ID('SP_NUEVOESTADOEQUIPO') IS NOT NULL
	DROP PROC SP_NUEVOESTADOEQUIPO
	PRINT 'PROC SP_NUEVOESTADOEQUIPO, HA SIDO PROCESADO'
GO

CREATE PROC SP_NUEVOESTADOEQUIPO
(
	@COD CHAR(6), @DES VARCHAR(100)
)
AS
	INSERT INTO ESTADO_EQUIPO VALUES(@COD, @DES)
GO

-- Procedimiento: Actualización de campos en registros en la tabla ESTADO_EQUIPO
IF OBJECT_ID('SP_ACTUALIZAESTADOEQUIPO') IS NOT NULL
	DROP PROC SP_ACTUALIZAESTADOEQUIPO
	PRINT 'PROC SP_ACTUALIZAESTADOEQUIPO, HA SIDO PROCESADO'
GO

CREATE PROC SP_ACTUALIZAESTADOEQUIPO
(
	@COD CHAR(6), @DES VARCHAR(100)
)
AS
	UPDATE ESTADO_EQUIPO SET
		DES_EST = @DES
		WHERE COD_EST = @COD
GO

-- Procedimiento: Eliminación de registros en la tabla ESTADO_EQUIPO
IF OBJECT_ID('SP_ELIMINAEESTADOQUIPO') IS NOT NULL
	DROP PROC SP_ELIMINAESTADOEQUIPO
	PRINT 'PROC SP_ELIMINAESTADOEQUIPO, HA SIDO PROCESADO'
GO
CREATE PROC SP_ELIMINAESTADOEQUIPO
(
	@COD CHAR(6)
)
AS
	DELETE ESTADO_EQUIPO WHERE COD_EST = @COD
GO

-- Scripts para los procedimientos almacenados
-- Tabla: TIPO_EQUIPO
-- ====================================================
USE CONTRATO
GO

-- Procedimiento: Lista TIPO_EQUIPO
IF OBJECT_ID('SP_LISTATIPOEQUIPOS') IS NOT NULL
	DROP PROC SP_LISTATIPOEQUIPOS
	PRINT 'PROC SP_LISTATIPOEQUIPOS, HA SIDO PROCESADO'
GO

CREATE PROC SP_LISTATIPOEQUIPOS
AS
	SELECT
		TE.COD_TIP_EQU AS CODIGO,
		TE.DES_TIP AS TIPO
		FROM TIPO_EQUIPO TE
GO

-- Procedimiento: Obtención del Código del último registro de la tabla TIPO_EQUIPO
IF OBJECT_ID('SP_ULTIMOTIPOEQUIPO') IS NOT NULL
	DROP PROC SP_ULTIMOTIPOEQUIPO
	PRINT 'PROC SP_ULTIMOTIPOEQUIPO, HA SIDO PROCESADO'
GO

CREATE PROC SP_ULTIMOTIPOEQUIPO
AS
	SELECT TOP 1
		TE.COD_TIP_EQU AS CODIGO
		FROM TIPO_EQUIPO TE
		ORDER BY 1 DESC
GO

-- Procedimiento: Ingreso de registros en la tabla TIPO_EQUIPO
IF OBJECT_ID('SP_NUEVOTIPOEQUIPO') IS NOT NULL
	DROP PROC SP_NUEVOTIPOEQUIPO
	PRINT 'PROC SP_NUEVOTIPOEQUIPO, HA SIDO PROCESADO'
GO

CREATE PROC SP_NUEVOTIPEQUIPO
(
	@COD CHAR(6), @DES VARCHAR(100)
)
AS
	INSERT INTO TIPO_EQUIPO VALUES(@COD, @DES)
GO

-- Procedimiento: Actualización de campos en registros en la tabla TIPO_EQUIPO
IF OBJECT_ID('SP_ACTUALIZATIPOEQUIPO') IS NOT NULL
	DROP PROC SP_ACTUALIZATIPOEQUIPO
	PRINT 'PROC SP_ACTUALIZATIPOEQUIPO, HA SIDO PROCESADO'
GO

CREATE PROC SP_ACTUALIZATIPOEQUIPO
(
	@COD CHAR(6), @DES VARCHAR(100)
)
AS
	UPDATE TIPO_EQUIPO SET DES_TIP = @DES
	WHERE COD_TIP_EQU = @COD
GO

-- Procedimiento: Eliminación de registros en la tabla TIPO_EQUIPO
IF OBJECT_ID('SP_ELIMINAETIPOQUIPO') IS NOT NULL
	DROP PROC SP_ELIMINAEQUIPO
	PRINT 'PROC SP_ELIMINATIPOEQUIPO, HA SIDO PROCESADO'
GO

CREATE PROC SP_ELIMINATIPOEQUIPO
(
	@COD CHAR(6)
)
AS
	DELETE TIPO_EQUIPO WHERE COD_TIP_EQU = @COD
GO
